### ISSUE TITLE
Installation without MacForge?

### ISSUE THREAD

**Issue by technicalpickles** [jslegendre/AfloatX#12]
Is it possible to install without MacForge? It has a pretty big warning about needing System Integrity Protection:

![image](https://user-images.githubusercontent.com/159/82949109-060f2c80-9f71-11ea-946f-8d3454f6e561.png)

I'm not sure I'm comfortable disabling that, especially with a work machine.

**Comment by sdyalor** [comment]
+1, any suggestions?

**Comment by sdyalor** [comment]
I have OpenCore, Just needed `sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true` whitout disabling SIP

**Comment by jslegendre** [comment]
Hi there! Unfortunately the only way to get AfloatX (or any other plugins) working on macOS is by using an injection platform and will require SIP to be disabled. I wouldn't recommend disabling SIP on a work machine because IF something happens, it won't matter to your company whether SIP would have saved you or not... Now, on your personal machine? Go for it! I've had it disabled since it was introduced and never had an issue
